### ISSUE TITLE
URL formatting error

### ISSUE THREAD

**Issue by FredStober** [PyCQA/docformatter#150]
After moving from v1.5.0 to v1.5.1, docformatter crashes while trying to format this URL in the documentation:
```
The text file can be retrieved via the Chrome plugin `Get
Cookies.txt <https://chrome.google.com/webstore/detail/get-
cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid>` while browsing
```

The stack trace points to this:
  File "...../docformatter/syntax.py", line 97, in do_preserve_links
    url = f"{indentation}" + url.strip().split(sep=" ")[1].strip()
IndexError: list index out of range

I saw that something similar was discussed in #140 after the ticket was closed - but the fix in PR 141 does not seem to touch that line of code.

**Comment by weibullguy** [comment]
@FredStober I got ahead of myself releasing 1.5.0 to PyPi without sufficient testing.  Before I cause users anymore headaches, I'm providing release candidates for the brave to use and provide feedback.  If you'd like to use the next release candidate that should resolve your issue, you can install it with pip:

`pip install git+https://github.com/PyCQA/docformatter.git@v1.6.0.rc1`

**Comment by FredStober** [comment]
Thank you - v1.6.0.rc1 does not crash anymore, but it does change the formatting in a few unexpected ways. Some of which will cause ping-pong changes when running yapf (in default pep8 mode) as well:

Long links are now wrapped between the URL and the description:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/3837576/213686442-1ac6b850-4d49-4773-ab66-71cd18f1ac1b.png">

The newline between code and docstring are not there anymore
<img width="115" alt="image" src="https://user-images.githubusercontent.com/3837576/213686674-80810baa-f3d9-40e2-94f5-34ad9b4aa0e1.png">
If a docstring is used as the only code element in a function, this will lead to pep8 issues like here:
<img width="129" alt="image" src="https://user-images.githubusercontent.com/3837576/213687084-b48fd774-c241-49af-92f1-fc9ef99b18d0.png">

Here, the original line was 74 chars long - and now it gets wrapped in a strange way:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/3837576/213687420-13d960da-e727-4160-a45d-b21bc1d7b7b9.png">

In this case it's not clear to me what is going on with the quotes:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/3837576/213687623-ba417f02-2bdb-4728-aa4d-be9f4185ab67.png">

sphinx-build will complain about "Unexpected indentation." in this case

**Comment by FredStober** [comment]
@weibullguy - do you want me to make new tickets for each issue, keep the discussion in here or move it to a single new ticket?

**Comment by weibullguy** [comment]
> Long links are now wrapped between the URL and the description: <img alt="image" width="466" src="https://user-images.githubusercontent.com/3837576/213686442-1ac6b850-4d49-4773-ab66-71cd18f1ac1b.png"> (which is fine I suppose...)

Hhhmmm, I actually used your docstring in a test and I get the following result, which I think is probably more what you're looking for.  I'll have to look into this some more.

```
-    The text file can be retrieved via the Chrome plugin `Get Cookies.txt <https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid>`
+    The text file can be retrieved via the Chrome plugin
+    `Get Cookies.txt <https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid>`
     while browsing.
     """
```

> The newline between code and docstring are not there anymore

Per PEP-257 there shouldn't be a newline before or after the docstring unless it's a class docstring.  Removing this newline is PEP-257 compliant.
 
> If a docstring is used as the only code element in a function, this will lead to pep8 issues like here: 

This is the same as above.  Putting a pass statement in the function with only the docstring should remedy this.  I also think that's the pythonic thing to do.

> Here, the original line was 74 chars long - and now it gets wrapped in a strange way: 

Agreed, it shouldn't do this.  I'll look into this some more.  I've re-opened this issue to address this and the first point above.

**Comment by weibullguy** [comment]
@FredStober I wish I had the brain power to think of every possible docstring by myself! ;)  Whenever someone includes their docstring in whole or in part, I write a test using that docstring (maybe I need an issue template).  So, if you want to provide the whole docstring that'd be great.

I did a little research and I've raised issue #154 to address the problem with stub functions and the `pass` statement.  Unfortunately, for now I can only offer two solutions in the interim:

1. Add the `pass` statement and suppress the pylint warning.
2. Run docformatter before yapf since this seems to straighten things out.

Thanks for taking the time to give the release candidate a try and providing feedback.

**Comment by weibullguy** [comment]
@FredStober I got it in my brain that the docstring you posted when you opened this issue was the resulting docstring:

```
The text file can be retrieved via the Chrome plugin `Get
Cookies.txt <https://chrome.google.com/webstore/detail/get-
cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid>` while browsing.
```

This was actually the original docstring and you didn't want it changed at all.  Is that correct?  

Currently, docformatter is looking for this situation:

```
`Get Cookies.txt <https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid>`
```

and not wrapping it, which is what most of the URL related issues are asking for.  So, in your case, it finds this `<https://chrome.google.com/webstore/detail/get-` as the URL and doesn't recognize that it starts and ends on the line before and after.  I think I have an idea how to handle this situation, I just want to confirm your desired output when the input docstring is as you posted it.

The issue with the `'s3://'` and `'file://'` I've taken care of.

**Comment by mr-josh** [comment]
:wave: Am experiencing some weird behaviour with indentation and URLs. If this is unrelated to this issue, let me know and I'll open a separate issue :)

I have the following docstring:
```python
        """
        Translates incoming json to a processable Entity.

        Stackoverflow reference: <https://stackoverflow.com/questions/69617489/can-i-get-incoming-extra-fields-from-pydantic>
        """
```

and running a format returns this diff.
```diff
@@ -37,7 +37,10 @@
         """
         Translates incoming json to a processable Entity.
 
-        Stackoverflow reference: <https://stackoverflow.com/questions/69617489/can-i-get-incoming-extra-fields-from-pydantic>
+        Stackoverflow reference:
+        
+        <https://stackoverflow.com/questions/69617489/can-i-get-incoming-extra-fields-from-pydantic>
+
         """
         built: dict[str, Any] = {
             "documentation": [],
```

The issue is the empty line having a bunch of white space added for no reason, and docformatter recognises this, since running the diff a second time after applying the first diff removes the white space as expected.

For reference, these are the settings I have in my `pyproject.toml`:
```toml
[tool.docformatter]
recursive = true
pre-summary-newline = true
wrap-summaries = 80
blank = true
```

**Comment by weibullguy** [comment]
@mr-josh what version of docformatter are you using?  I get the following result using 1.6.0-rc2 (with only one pass):

```
     """
     Translates incoming json to a processable Entity.
 
-    Stackoverflow reference: <https://stackoverflow.com/questions/69617489/can-i-get-incoming-extra-fields-from-pydantic>
+    Stackoverflow reference:
+    <https://stackoverflow.com/questions/69617489/can-i-get-incoming-extra-fields-from-pydantic>
     """
```

**Comment by mr-josh** [comment]
@weibullguy `docformatter==1.5.1`. If it's not an issue in 1.6.0 then can wait for release.

**Comment by weibullguy** [comment]
@symonk Thanks for the feedback.
