### ISSUE TITLE
Add a  `--exit` flag to see if files changed

### ISSUE THREAD

**Issue by Trim21** [PyCQA/docformatter#40]
I'd like to use `docformatter` in my `pre-commit` hooks, and i want it to format my docstring when pre commit hook called, so i use `-i` flag in my config.

(If `--check` flag, I have to manually format it again after hooks failure, seems unnecessary)

But i found that exit code is always 0 even it has changed file content, and `--check` flag can't be used with `-i` flag.

Is there any possibility to add a `--exit` flag or something to let `docformatter` exit with not `0` when `docformatter` changed file content?

**Comment by mdczaplicki** [comment]
It actually works like you want (and like I don't want), that it returns non-zero when it modifies a file.
```
docformatter.............................................................Failed
- hook id: docformatter
- files were modified by this hook
```
I would like it to Pass even if it modifies a file :stuck_out_tongue:

**Comment by weibullguy** [comment]
@mdczaplicki, I believe it's pre-commit returning the non-zero exit code when a hook changes a file.  See [here](https://github.com/pre-commit/pre-commit/blob/9c55cc3954ecdacc288fba5deaa67d65bbd5972b/pre_commit/commands/run.py#L196).  A new `docformatter` exit code won't alleviate the pre-commit behavior.  In September 2019, pre-commit returned an exit code of 1 if files were changed, so the pre-commit behavior @Trim21 wants existed at the time this issue was opened as well.

Is there some use-case for docformatter returning a non-zero exit code when files are modified in place independent of pre-commit?

**Comment by Trim21** [comment]
sorry I haven't used Python for a long time, I have forgotten why I open this issue……

It looks like pre-commit and this tools works fine.
