### ISSUE TITLE
Readme example does not produce the expected result

### ISSUE THREAD

**Issue by m-richards** [PyCQA/docformatter#67]
In the readme, an example using the syntax `docformatter --in-place example.py` is used, and suggests that 
```
def launch_rocket():
    """Launch
the
rocket. Go colonize space."""
```
is autoformatted to 
```
def launch_rocket():
    """Launch the rocket.

    Go colonize space.
    """
```
. This is not the case unless one runs `docformatter --in-place --force-wrap example.py` (this function is unchanged). As far as I can tell this happens due to the use heuristic ratio detection in `is_some_sort_of_list`

This isn't exactly a problem as one can just enable the flag, but may be worth making that explicit in the example. Not sure if there could be a better solution (maybe the first line of a docstring shouldn't be parsed as a list?) but I'm a new user so not sure what the desired behaviour should be.

**Comment by weibullguy** [comment]
Per PEP-257, a one-line docstring "...is a phrase ending in a period."  and "Multi-line docstrings consist of a summary line just like a one-line docstring, followed by a blank line, followed by a more elaborate description."  Thus, docformatter should provide the expected results without the `--force-wrap` flag.  The first period should be interpreted as the end of the summary line and anything following would be the elaborate description.

**Comment by weibullguy** [comment]
In the function that checks the docstring text for lists, there is a conditional block with the comment:

```
# Very large number of lines but short columns probably means a list of
# items.
```

This conditional is the cause of the example not working without the --force-wrap argument being set.  Since --force-wrap will cause even real lists to be wrapped, that can't be an acceptable work around.  The conditional has existed since 2014, but there is no issue or PR associated with the commit adding it.  The condition it checks for does not represent a reST list format and the remainder of the is_some_sort_of_list() function checks for standard reST patterns that indicate a list.

The easy solution is to delete the conditional since it's looking for non-reST patterns to indicate a list.  However, since the basis for the conditional is unknown, a --strict argument will be added for now to ensure existing use-cases aren't impacted.  Setting this to false will continue to check for  a large number of short lines to indicate a list, the default will be true.
